//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 游戏刚开始时空手只能采到木头，所以要先用木材制作木镐。再使用木镐到附近的山上采石头，如果附近没有山，也可以直接挖脚下，从脚下也可以采到石头。使用3块圆石和2根木棍可以制作石镐，再用石镐就可以快速挖矿洞采其它类型的矿产了。可以通过找现成的矿洞或者自己挖矿洞的方法采矿。找到铁矿】
        ///
        ///因为开采红石矿必须使用铁镐等级以上的工具，使用石镐只会破坏矿石而得不到红石，所以要提前制作几把铁镐。先找到铁矿，采一些铁矿石备用。【制作铁镐】
        ///
        ///使用3块铁矿石和2根木棍可以制作铁镐，用铁镐就可以去采红石矿了。【找到红石矿】
        ///
        ///红石矿在较深的位置，所以建议深入到16层以下去开采红石。红石矿的颜色比较容易辨认，一般红石矿是成片的，所以挖矿时建议把四周都挖一下，也许就能找到更多的红石矿。开采红石】
        ///
        ///使用铁镐就能采到红石了，一个红石矿大概可以采到1-3块红石。红石的数量当然是多多益善，建议多采一些红石备用。【存储红石】
        ///
        ///采到的红石建议保留在家里的箱子中，最好不要随手携带，否则一旦遇到怪物死亡，可能随身带的重要物品都无法找回了。 的本地化字符串。
        /// </summary>
        internal static string 我的世界红石怎么获得 {
            get {
                return ResourceManager.GetString("我的世界红石怎么获得", resourceCulture);
            }
        }
    }
}
